In [26]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B-Instruct")
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.2-1B-Instruct")

In [27]:
# 質問の入力
tokenizer.pad_token = tokenizer.eos_token
tokenizer.pad_token_id = tokenizer.eos_token_id

device='cuda'
question = "what is the llm？ explain 1 sentence."
input_ids = tokenizer(question, return_tensors="pt", truncation=True, padding=True).to(device)
model.to(device)

attention_mask=input_ids['attention_mask']
print(attention_mask, input_ids)

output = model.generate(input_ids['input_ids'], attention_mask=attention_mask, pad_token_id=tokenizer.eos_token_id)
print(output)

# 出力のデコード
answer = tokenizer.decode(output[0], skip_special_tokens=True)
print(answer)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:0') {'input_ids': tensor([[128000,  12840,    374,    279,   9507,     76,  11571,  10552,    220,
             16,  11914,     13]], device='cuda:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:0')}
tensor([[128000,  12840,    374,    279,   9507,     76,  11571,  10552,    220,
             16,  11914,     13,    362,   4221,   1646,    374,    264,   6500,
           2068,   6319]], device='cuda:0')
what is the llm？ explain 1 sentence. A language model is a computer program designed


/root/miniconda3/envs/my-env/lib/python3.9/site-packages/transformers/generation/utils.py:1220: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


In [59]:
question = "a b"
input_ids = tokenizer(question, return_tensors="pt", truncation=True, padding=True).to(device)
output = model(input_ids['input_ids'], attention_mask=attention_mask)
print(output.logits.size())

torch.Size([1, 3, 128256])


In [60]:
import torch
probabilities = torch.softmax(output.logits[0][2], dim=-1)
print(probabilities)
predicted_token_ids = torch.argmax(probabilities, dim=-1)
print(predicted_token_ids)
decoded_text = tokenizer.decode(predicted_token_ids, skip_special_tokens=True)
print(decoded_text)

tensor([3.3344e-06, 1.1764e-06, 8.8509e-07,  ..., 7.4480e-10, 7.4465e-10,
        7.4483e-10], device='cuda:0', grad_fn=<SoftmaxBackward0>)
tensor(272, device='cuda:0')
 c
